!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  P1: 200.0
  P2: 400.0
  correlation_window_size: 9
  disp12MaxDiff: 0
  disparity_range: 176
  fullDP: false
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      P1: 200.0
      P2: 400.0
      correlation_window_size: 9
      disp12MaxDiff: 0
      disparity_range: 176
      fullDP: false
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      min_disparity: 8
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      prefilter_cap: 31
      prefilter_size: 11
      speckle_range: 7
      speckle_size: 480
      state: true
      stereo_algorithm: 1
      texture_threshold: 100
      type: ''
      uniqueness_ratio: 6.0
    state: []
  min_disparity: 8
  prefilter_cap: 31
  prefilter_size: 11
  speckle_range: 7
  speckle_size: 480
  stereo_algorithm: 1
  texture_threshold: 100
  uniqueness_ratio: 6.0
state: []
