!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  P1: 200.0
  P2: 400.0
  correlation_window_size: 15
  disp12MaxDiff: 0
  disparity_range: 144
  fullDP: false
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      P1: 200.0
      P2: 400.0
      correlation_window_size: 15
      disp12MaxDiff: 0
      disparity_range: 144
      fullDP: false
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      min_disparity: 2
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      prefilter_cap: 16
      prefilter_size: 13
      speckle_range: 10
      speckle_size: 480
      state: true
      stereo_algorithm: 0
      texture_threshold: 50
      type: ''
      uniqueness_ratio: 3.0
    state: []
  min_disparity: 2
  prefilter_cap: 16
  prefilter_size: 13
  speckle_range: 10
  speckle_size: 480
  stereo_algorithm: 0
  texture_threshold: 50
  uniqueness_ratio: 3.0
state: []
